version: 0.2
phases:
  install:
    commands:
      - echo install step...
      - pip install --upgrade awscli==1.18.17
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t qukka-stage:latest .
      - docker tag qukka-stage:latest 107082111359.dkr.ecr.ap-southeast-1.amazonaws.com/qukka-stage:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 107082111359.dkr.ecr.ap-southeast-1.amazonaws.com/qukka-stage:latest
      - printf '[{"name":"node-stage-api","imageUri":"%s"}]' 107082111359.dkr.ecr.ap-southeast-1.amazonaws.com/qukka-stage:latest > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
